apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ilonkasie-poi-map-app-dev
  annotations:
    argocd/app-name: ilonkasie-poi-map-app-dev
    backstage.io/kubernetes-id: ilonkasie-poi-map-app
    backstage.io/kubernetes-namespace: ilonkasie
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh23-lab/ilonkasie-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-m9x67.dusy.p1.openshiftapps.com/dev-pipelines/ns/ilonkasie/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-m9x67.dusy.p1.openshiftapps.com/k8s/ns/ilonkasie/deployments/ilonkasie-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-m9x67.dusy.p1.openshiftapps.com/#https://github.com/rhdh23-lab/ilonkasie-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://ilonkasie-poi-map-app-ilonkasie.apps.rosa-m9x67.dusy.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/ilonkasie"
  system: workshop-system-ilonkasie
  consumesApis:
    - gateway-api-ilonkasie
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-ilonkasie
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/ilonkasie"
